# Generated by Django 5.2.7 on 2025-10-30 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст запитання')),
                ('tipe', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення'), ('video', 'Відео')], default='text', max_length=10, verbose_name='Тип запитання')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильна відповідь')),
                ('file', models.FileField(blank=True, null=True, upload_to='questions/', verbose_name='Файл (зображення/відео)')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choose', models.CharField(max_length=255, verbose_name='Варіант відповіді')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильний')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва вікторини')),
                ('complexity', models.CharField(choices=[('easy', 'Легка'), ('medium', 'Середня'), ('hard', 'Складна')], default='medium', max_length=20, verbose_name='Складність')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема')),
                ('que_time', models.PositiveIntegerField(default=30, verbose_name='Час на запитання (сек)')),
                ('que_count', models.PositiveIntegerField(default=10, verbose_name='Кількість запитань')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Бали')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
