# Generated by Django 5.2.7 on 2025-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=15, verbose_name='Час на питання (сек)'),
        ),
    ]
