# Generated by Django 5.2.7 on 2026-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizroom_quizplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizplayer',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
