# Generated by Django 5.2.7 on 2026-01-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizplayer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
