# Generated by Django 5.2.7 on 2026-01-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_invite_code_alter_question_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='invite_code',
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='questions/', verbose_name='Файл (зображення/відео)'),
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizplayer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
    ]
