# Generated by Django 5.2.7 on 2026-01-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_invite_code_alter_question_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerAnswer',
        ),
    ]
