# Generated by Django 5.2.7 on 2026-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_delete_playeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizplayer',
            name='answered_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizroom',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizroom',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
