# Generated by Django 5.2.7 on 2026-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizplayer_answered_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='que_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='que_time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
